apiVersion: v1
kind: Service
metadata:
  name: openkyc-service
  namespace: openkyc
spec:
  selector:
    app: openkyc-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
